### ISSUE TITLE
[Feature Request] Permanent Install Fedora into SD Card

### ISSUE THREAD

**Issue by duytrung** [lmacken/liveusb-creator#15]
Hi,

I'm just wonder is it possible to implement a functionality that allow LiveUSB-Creator to:
1. Create a Swap and Linux file system partitions in a dedicated high speed SD Card.
2. Install Fedora into the SD Card. Then install the boot manager as we normally install Fedora in a desktop computer.

So that we can boot Fedora from SDCard without touching the main partition?

I have used Fedora for long time and not consider switching to other distros. This is a feature I'm after for a long long time. 

Thanks for recommendation.

Regards

**Comment by lmacken** [comment]
I think this is out of the scope of the liveusb-creator itself, because Anaconda does this already. I've heard from some Sugar folks who use it to install directly to SD cards in the way you described. So, I'd recommend taking the DVD or server isos and use Anaconda to install to your USB key.
