### ISSUE TITLE
needs better icon

### ISSUE THREAD

**Issue by andreasn** [lmacken/liveusb-creator#17]
So I only saw a quick demo, but the application icon looked a bit funky.
I would be happy to make a new one.

**Comment by aruiz** [comment]
I'm attaching a screenshot for reference.

![screenshot from 2015-03-19 15 35 58](https://cloud.githubusercontent.com/assets/2845/6734024/b56de54a-ce4d-11e4-9b49-73efe7602892.png)

**Comment by lmacken** [comment]
Fixed in the develop branch. Thanks for the report!
