### ISSUE TITLE
Liveusb-Creator precentage bar lies when transfering osmin.img

### ISSUE THREAD

**Issue by gregjurman** [lmacken/liveusb-creator#2]
When creating a stick, liveusb-creator states that the image has been copied at an incredibly unreasonable speed then marks the percentage indicator at 99%. It then stays at installing bootloader for what is the reasonable amount of time to copy the image file.

```
Extracting live image to USB device...
Wrote to device at 1361 MB/sec
Installing bootloader...
```

**Comment by MartinBriza** [comment]
Fixed in some of the newer commits. The progressbars now report the actual size of the data written, not just an approxmiation
