### ISSUE TITLE
TypeError: coercing to Unicode: need string or buffer, NoneType found

### ISSUE THREAD

**Issue by 0vermind** [lmacken/liveusb-creator#24]
On Ubuntu 15.04 I installed liveusb-creator-3.13.2.
When I try to make a persistent usb key not using DD mode (non-destructive cp) I get this error:

> Traceback (most recent call last):
>   File "/home/user/liveusb-creator-3.13.2/liveusb/gui.py", line 535, in begin
>     elif not self.live.mbr_matches_syslinux_bin():
>   File "/home/user/liveusb-creator-3.13.2/liveusb/creator.py", line 938, in mbr_matches_syslinux_bin
>     mbr_bin = open(self._get_mbr_bin(), 'rb')
> TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by MartinBriza** [comment]
Thanks for reporting! This bug is no longer present with the new UI overhaul but please feel free to keep the reports coming.
