### ISSUE TITLE
Resolve the difference between the device and a partition (and maybe make formatting possible)

### ISSUE THREAD

**Issue by MartinBriza** [lmacken/liveusb-creator#29]
Currently, there is a confusing duality regarding the partitions and devices.
You can have more FAT32 partitions on one flash drive. Or, you can have none.
Either way, the way we handle this currently confuses the user.
Hand in hand with this is the possibility to format the drives directly from the tool, to make the process even more straightforward.

**Comment by mikedep333** [comment]
I believe this is the issue that I experienced last night. I mentioned it to @lmacken on #fedora-apps.'

IMHO, A "4.2 MB" USB key would likely confuse the user. Especially if they have 2 USB keys of the same brand, but of a different capacity (e.g., 4 GB& 16GB. They might format the 16GB by mistake if it showed up as "4.2 MB".)

screenshots on F23: https://imgur.com/a/varEz
MBR: http://s000.tinyupload.com/index.php?file_id=00153657459872261567

**Comment by MartinBriza** [comment]
This was resolved when switched to dd-only mode.
