### ISSUE TITLE
CPU 80-100 % when downloading

### ISSUE THREAD

**Issue by frafra** [lmacken/liveusb-creator#30]
As soon as I start to download, liveusb-creator uses almost all my CPU. No pendrive plugged.

$ rpm -q liveusb-creator
liveusb-creator-3.15.0-0.1.newui.20151102git857190d6.fc23.noarch

**Comment by MartinBriza** [comment]
Fixed by 71ab5355f4d70fe90435756773efceb6e74e48dd
