### ISSUE TITLE
Missing support for qhd displays

### ISSUE THREAD

**Issue by NVolcz** [lmacken/liveusb-creator#42]
The UI scales terrible on high resolution displays.
[http://imgur.com/mlpHwQJ](http://imgur.com/mlpHwQJ)

**Comment by MartinBriza** [comment]
Please try running a recent version of the tool and report your findings. This is really outdated.

**Comment by MartinBriza** [comment]
There was no reply for about a week and I think there actually is some high DPI support though, as tested by myself - closing. If you experience scaling issues, please feel free to report another bug.
