### ISSUE TITLE
Runtime Error on Windows 10

### ISSUE THREAD

**Issue by okgolove** [lmacken/liveusb-creator#59]
* Just open latest release and wait for 5-10 seconds.
* You'll get an error:
![image](https://user-images.githubusercontent.com/36846182/37252243-8b2cbf1c-2526-11e8-995b-8f5a906342b1.png)

**Comment by MartinBriza** [comment]
Please try using Fedora Media Writer from here: https://github.com/MartinBriza/MediaWriter
It looks and works mostly the same, except it's now the official way to download and write Fedora to your flash drive - you can get a slightly older version from https://getfedora.org .
